version: "3"

networks:
  my-network:

services:

  appdjango:
    container_name: clasewebdjango
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    networks:
      - my-network
